### PR TITLE
Added new interception point: "postLogin"

### PR DESCRIPTION
**Pull request by homestar9**
You might be asking yourself, why do we need another interception point?  Good question!  Adding a new interception point for "postLogin" will allow applications which will log a user in by calling `auth().logIn()` explicitly instead of `auth().authenticate()` to perform important post-login actions.  This would be especially useful for a site that has "remember me" functionality, where a user will be logged in based on a special cookie on their browser as opposed to them entering their username/password.

### CODE REVIEW

**Comment by elpete** [comment]
I like it.  Can you add a `preLogin` interception point for symmetry and also document both in the `README.md`?

**Comment by elpete** [comment]
The tests for interception points will also need to be updated to check for the new events.  Thanks!

**Comment by homestar9** [comment]
You got it. I'll take care of those ASAP.  I'm still a bit of a noob when it comes to writing integration tests but I will figure it out. :)

**Comment by elpete** [comment]
The test is already written.  Find the currently failing test in this branch and add the new interceptor expectations there.

**Comment by homestar9** [comment]
All set! Feel free to change the readme.md if you prefer an alternate description.

**Comment by elpete** [comment]
Thanks for all your work on this!

**Comment by elpete** [comment]
Available now as [`4.1.0`](https://github.com/coldbox-modules/cbauth/releases/tag/v4.1.0)

**Comment by homestar9** [comment]
You're welcome, thanks for creating such awesome modules.  Have a great holiday!

**Pull request merged**
