### PR TITLE
Multiple fixes

### PR DESCRIPTION
**Pull request by lmajano**
This pull request has the following:

1) Doc blocks 
2) Updated docs
3) Added preLogout/postLogout interception points
4) Fixed issue where preLogin/postLogin where not registered as interception points
5) CFFormatting goodness
6) More Tests
7) Added the coldbox convention for loading helpers
8) API Docs generation and sending to s3

### CODE REVIEW

**Comment by elpete** [comment]
Just need to `box run-script format`, commit the changes, and push.

**Comment by lmajano** [comment]
@elpete the formatting is not using our standard, look at the image:

image

**Comment by elpete** [comment]
I used the standards found in quick and qb. Since it is just a `format` command away, that shouldn’t be a problem.

**Comment by lmajano** [comment]
please check now @elpete

**Pull request merged**
